[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
