[build]
  command = "npm --prefix parkos/netlify/functions install"
  publish = "parkos/public"
  functions = "parkos/netlify/functions"

[[redirects]]
  from = "/api"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
